uploads = []
outputs = []

[[generated]]
id = "LTDc8cUo_xwTFx2Dct8y8"
uri = "file://client/src/assets/images/hero-bg.png"
type = "image"
title = "generated_image"

[[generated]]
id = "aquJmBfg_aJbK0RecIvHh"
uri = "file://client/src/assets/images/project-sober.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gYutigJMMpWBrGN-5ZFv-"
uri = "file://src/assets/images/hero-bg.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RH7-olHKR1IpwowSeWxO5"
uri = "file://src/assets/images/project-sober.png"
type = "image"
title = "generated_image"
